# Open API 버전 (주로 3.0.0을 이용한다.)
openapi: 3.0.0

# API 문서에 대한 정보 (버전, 제목, 설명)
info:
  version: '1.0.0'
  title: '왓섭큐'
  description: '2030 1인 가구를 위한 맞춤형 이커머스'
  
# API 서버에 대한 정보
servers:
  #- url: "http://54.180.46.143:3000/api"
  - url: "http://localhost:3000/api"
    description: 왓섭큐 API # 제공하는 API에 대한 설명

tags:
  - name: 상품
    description: 상품 (메인 페이지)
  - name: 로그인 및 회원가입
    description: 로그인 및 회원가입 관련
  - name: 마이페이지
    description: 마이페이지 관련
  - name: 결제
    description: 결제 관련

# 각 URI에 대한 정보를 기재
paths:
  /product/main:
    $ref: './paths/product/main.yaml'
  /product/regular:
    $ref: './paths/product/regular.yaml'
  /product/themabox:
    $ref: './paths/product/themabox.yaml'
  /product/regular/detail:
    $ref: './paths/product/regular_detail.yaml'
  /product/package/detail:
    $ref: './paths/product/package_detail.yaml'
  /product/custom:
    $ref: './paths/product/custom.yaml'

  /auth/signin:
    $ref: './paths/auth/signin.yaml'
  /auth/signup: 
    $ref: './paths/auth/signup.yaml'
  /auth/findID: 
    $ref: './paths/auth/findID.yaml'
  /auth/findPW: 
    $ref: './paths/auth/findPW.yaml'
  /auth/REsignin: 
    $ref: './paths/auth/REsignin.yaml'

  /mypage/user:
    $ref: './paths/mypage/user.yaml'
  /mypage/order:
    $ref: './paths/mypage/order.yaml'
  /mypage/order/delivery:
    $ref: './paths/mypage/delivery.yaml'


  /mypage/regular-delivery/change/address:
    $ref: './paths/mypage/regular-delivery/change/address.yaml'
  /mypage/regular-delivery/change/count-minus:
    $ref: './paths/mypage/regular-delivery/change/count-minus.yaml'
  /mypage/regular-delivery/change/count-plus:
    $ref: './paths/mypage/regular-delivery/change/count-plus.yaml'
  /mypage/regular-delivery/change/memo:
    $ref: './paths/mypage/regular-delivery/change/memo.yaml'
  /mypage/regular-delivery/change/cycle:
    $ref: './paths/mypage/regular-delivery/change/cycle.yaml'
  /mypage/regular-delivery/change/delivery-day:
    $ref: './paths/mypage/regular-delivery/change/delivery-day.yaml'
  /mypage/regular-delivery/change/cancel:
    $ref: './paths/mypage/regular-delivery/change/cancel.yaml'

  /payment/card-enrollment:
    $ref: './paths/payment/card-enrollment.yaml'
  /payment/card:
    $ref: './paths/payment/card.yaml'
  /payment/card-payment:
    $ref: './paths/payment/card-payment.yaml'
